title: wanzhebufangqiのblog
header-img: img/post-bg-desk.png
email: wangzhebufangqi@hnu.edu.cn
description: 不管过了几载春秋，我还是会偶尔想起
keyword: "wangzhebufangqi, 就算过了一载春秋"
url: "http://wangzhebufangqi.github.io"
github_repo: "https://github.com/wangzhebufangqi/wangzhebufangqi.github.io.git"

# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "等待热泪盈眶的那一天"
sidebar-avatar: /img/avatar-touxiang.png


# SNS settings
RSS: false
# weibo_username:     
zhihu_username:     dan-ran-shi-jie
github_username:    wangzhebufangqi
#facebook_username:  
jianshu_username:   4cc00ff26ffe
csdn_username:      qq_40889820
#twitter_username:   
qq_number:          1823636309


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`




# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "WilliamWuLH",
        href: "https://github.com/WilliamWuLH"
    },{
        title: "longkejie",
        href: "https://github.com/longkejie"
    }
]